[BugFix] Fix unintended parsing tool calls (#3001)
# Description

Fix unintended parsing tool calls

Error: [Use GPT Function Calling-04-25-2024-12-19-14 - Azure AI |
Machine Learning
Studio](https://ml.azure.com/prompts/flow/f8925d22-478a-4b5c-8e16-a85158d03b9b/addd3ee1-583a-4a67-a76f-7f6a0dedcc42/details?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourceGroups/promptflow/providers/Microsoft.MachineLearningServices/workspaces/promptflow-eastus-dev&tid=72f988bf-86f1-41af-91ab-2d7cd011db47)

![image](https://github.com/microsoft/promptflow/assets/46446115/744a6643-6b6b-4e1c-9180-2aec934f826d)

Same experiment run success after fix:

https://ml.azure.com/prompts/flow/f8925d22-478a-4b5c-8e16-a85158d03b9b/cd75a85c-33d5-4348-8e8c-ed6fc392c3b4/details?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourceGroups/promptflow/providers/Microsoft.MachineLearningServices/workspaces/promptflow-eastus-dev&tid=72f988bf-86f1-41af-91ab-2d7cd011db47


Run tool sample with fix:

https://ml.azure.com/prompts/flow/f8925d22-478a-4b5c-8e16-a85158d03b9b/3e2c30b8-d41e-4114-adb3-0f180fcbc6fe/details?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourcegroups/promptflow/providers/Microsoft.MachineLearningServices/workspaces/promptflow-eastus-dev&flight=pfnewllm,pfflowleveltool&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

# All Promptflow Contribution checklist:
- [X] **The pull request does not introduce [breaking changes].**
- [ ] **CHANGELOG is updated for new features, bug fixes or other
significant changes.**
- [X] **I have read the [contribution guidelines](../CONTRIBUTING.md).**
- [ ] **Create an issue and link to the pull request to get dedicated
review from promptflow team. Learn more: [suggested
workflow](../CONTRIBUTING.md#suggested-workflow).**

## General Guidelines and Best Practices
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an
informative message. This means that previously merged commits do not
appear in the history of the PR. For more information on cleaning up the
commits in your PR, [see this
page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### Testing Guidelines
- [X] Pull request includes test coverage for the included changes.

---------

Co-authored-by: yalu4 <yalu4@microsoft.com>