Fix ut "test_concurrent_execution_of_refresh_connections_dir" with TypeError: refresh_connections_dir() missing 1 required positional argument: 'connection_template_yamls' (#858)
# Description

Error in sdk_cli_test CI: TypeError: refresh_connections_dir() missing 1
required positional argument: 'connection_template_yamls'

Failed reason: 
The error you're seeing is due to incorrect argument passing in your
threading.Thread line. You're trying to pass arguments to
refresh_connections_dir as a dictionary, but this function expects two
positional arguments.

The correct way to provide arguments to the target function in
threading.Thread is to use a **tuple**. In your case, since
refresh_connections_dir requires two arguments, you should provide a
tuple of two elements.

Solution:

![image](https://github.com/microsoft/promptflow/assets/46446115/ac2cf6fe-2c11-4f6c-9d49-b6d12cce230f)

Co-authored-by: yalu4 <yalu4@microsoft.com>