[Flow Test] Fix node test failed with dict input (#1166)
# Description

```
[2023-11-16 15:02:27,374][promptflow][INFO] - Command ran in 14.527 seconds (init: 0.131, invoke: 14.396)
Traceback (most recent call last):
  File "D:\Project\github_promptflow\promptflow\src\promptflow\promptflow\_cli\_pf\_flow.py", line 410, in test_flow
    result = pf_client.flows.test(
  File "D:\Project\github_promptflow\promptflow\src\promptflow\promptflow\_telemetry\activity.py", line 138, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Project\github_promptflow\promptflow\src\promptflow\promptflow\_sdk\operations\_flow_operations.py", line 73, in test
    result = self._test(
  File "D:\Project\github_promptflow\promptflow\src\promptflow\promptflow\_sdk\operations\_flow_operations.py", line 131, in _test
    flow_inputs, dependency_nodes_outputs = submitter.resolve_data(
  File "D:\Project\github_promptflow\promptflow\src\promptflow\promptflow\_sdk\operations\_test_submitter.py", line 142, in resolve_data
    raise UserErrorException(f'Required input(s) {missing_inputs} are missing for "{prefix}".')
promptflow.exceptions.UserErrorException: Required input(s) ['key'] are missing for "print_val2".
```
Please add an informative description that covers that changes made by
the pull request and link all relevant issues.

# All Promptflow Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes].**
- [ ] **CHANGELOG is updated for new features, bug fixes or other
significant changes.**
- [ ] **I have read the [contribution guidelines](../CONTRIBUTING.md).**
- [ ] **Create an issue and link to the pull request to get dedicated
review from promptflow team. Learn more: [suggested
workflow](../CONTRIBUTING.md#suggested-workflow).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an
informative message. This means that previously merged commits do not
appear in the history of the PR. For more information on cleaning up the
commits in your PR, [see this
page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### Testing Guidelines
- [ ] Pull request includes test coverage for the included changes.